---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu-12.04
    box_url: https://mopub-virtual-machines.s3.amazonaws.com/ubuntu-12.04.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
suites:
- name: notrunning
  run_list:
  - recipe[haproxy_lwrp::test_haproxy_not_running]
  attributes: {}
- name: basictest
  run_list:
  - recipe[haproxy_lwrp::test_haproxy_basictest]
  attributes: {}
- name: carbontest
  run_list:
  - recipe[haproxy_lwrp::test_carbontest]
  attributes: {}
